"""Default role and permission seed data."""

DEFAULT_ROLES = [
    ("SUPER_ADMIN", "Super Admin", "Full system access"),
    ("ADMIN", "Admin", "Administrative access"),
    ("PRINCIPAL", "Principal", "School principal access"),
    ("TEACHER", "Teacher", "Teacher access"),
    ("ACCOUNTANT", "Accountant", "Finance access"),
    ("ADMISSION_OFFICER", "Admission Officer", "Admissions access"),
    ("STUDENT", "Student", "Student access"),
    ("PARENT", "Parent", "Parent access"),
]

DEFAULT_PERMISSIONS = [
    ("users.create", "users", "create"),
    ("users.read", "users", "read"),
    ("users.update", "users", "update"),
    ("users.delete", "users", "delete"),
    ("classes.create", "classes", "create"),
    ("classes.read", "classes", "read"),
    ("classes.update", "classes", "update"),
    ("classes.delete", "classes", "delete"),
    ("inquiries.create", "inquiries", "create"),
    ("inquiries.read", "inquiries", "read"),
    ("inquiries.update", "inquiries", "update"),
    ("inquiries.approve", "inquiries", "approve"),
    ("inquiries.reject", "inquiries", "reject"),
    ("inquiries.review", "inquiries", "review"),
    ("interviews.read", "interviews", "read"),
    ("interviews.schedule", "interviews", "schedule"),
    ("interviews.update", "interviews", "update"),
    ("students.create", "students", "create"),
    ("students.read", "students", "read"),
    ("students.update", "students", "update"),
    ("students.delete", "students", "delete"),
    ("admissions.create", "admissions", "create"),
    ("admissions.read", "admissions", "read"),
    ("admissions.update", "admissions", "update"),
    ("admissions.approve", "admissions", "approve"),
    ("admissions.reject", "admissions", "reject"),
    ("admissions.verify_documents", "admissions", "verify_documents"),
    ("enrollment.create", "enrollment", "create"),
    ("teachers.create", "teachers", "create"),
    ("teachers.read", "teachers", "read"),
    ("teachers.update", "teachers", "update"),
    ("teachers.salary.pay", "teachers", "salary.pay"),
]

ROLE_PERMISSION_MAP: dict[str, list[str]] = {
    "SUPER_ADMIN": [p[0] for p in DEFAULT_PERMISSIONS],
    "ADMIN": [p[0] for p in DEFAULT_PERMISSIONS],
    "PRINCIPAL": [
        "classes.read",
        "inquiries.read",
        "inquiries.review",
        "inquiries.reject",
        "interviews.read",
        "interviews.schedule",
        "interviews.update",
        "students.read",
        "admissions.read",
        "admissions.approve",
        "admissions.reject",
        "admissions.verify_documents",
        "enrollment.create",
        "teachers.read",
    ],
    "TEACHER": ["classes.read", "students.read", "teachers.read", "interviews.read"],
    "ACCOUNTANT": ["teachers.read", "teachers.salary.pay"],
    "ADMISSION_OFFICER": [
        "classes.read",
        "inquiries.create",
        "inquiries.read",
        "inquiries.update",
        "inquiries.reject",
        "inquiries.review",
        "interviews.read",
        "interviews.schedule",
        "interviews.update",
        "students.create",
        "students.read",
        "students.update",
        "admissions.create",
        "admissions.read",
        "admissions.update",
        "admissions.verify_documents",
        "enrollment.create",
    ],
    "STUDENT": ["students.read"],
    "PARENT": ["inquiries.create", "students.read"],
}
